stages:
- build-test
- deploy-master

build-test:
  stage: build-test
  services:
  - mysql:5.7
  variables:
    MYSQL_DATABASE: "database_test"
    MYSQL_ROOT_PASSWORD: null 
  tags:
  - web
  image: node:latest
  script:
  - npm install
  - npm run test
  only:
  - master
  - develop
  - /^(\d+)-.*$/

deploy-master:
  stage: deploy-master
  image: deployer:latest
  tags:
  - web
  before_script:
  - apk update
  - apk add openssh
  script:
  - ssh ubuntu@gajiandulu-admin.projects.refactory.id -o StrictHostKeyChecking=no 'cd /home/ubuntu/apps/gajiandulu && sudo -u www-data bash -s deploy.sh'
  only:
  - master

